---
title: Jeff Wilkey
position: Full Stack Web Developer
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
  values:
    layout: default
email: contact@jeffwilkey.com
tagline: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
paginate: 7
paginate_path: "/blog/:num/"
baseurl: 
url: 
twitter_username: jeffwilkey
github_username: jeffwilkey
linkedin_username: jeffwilkey
work_availability: Available
plugins:
- jekyll-feed